### ISSUE TITLE
Crashes on Refresh of Contacts

### ISSUE THREAD

**Issue by indivisable** [edwardvalentini/EVContactsPicker#10]
Hello I seem to have fixed a bug that was troubling me for the past few weeks.

On iPhone 6 with test contacts the bug did not show but only on iPhone 7 Plus with real (my personal) contact list did it occur.

I was able to fix it by updating the following code:

https://github.com/edwardvalentini/EVContactsPicker/blob/master/Pod/Classes/EVContactsPickerViewController.swift#L279

```
if(tmpContact.imageDataAvailable) {
                        if let imgData = tmpContact.imageData {
                            let img = UIImage(data: imgData)
                            mutableContact.image = img
                        } else {
                            mutableContact.image = self.avatarImage
                        }
                    } else {
                        mutableContact.image = self.avatarImage
                    }
```

Basically we should check if their is data similar to how same as it is done above (https://github.com/edwardvalentini/EVContactsPicker/blob/master/Pod/Classes/EVContactsPickerViewController.swift#L224)

**Comment by edwardvalentini** [comment]
wow this looks great… do you want to submit a PR then I can merge it?

**Comment by indivisable** [comment]
Sure I'll make a PR first thing tomm, I have some other changes I did too that I will go through and see what is worth adding. Thanks for the great library!

**Comment by indivisable** [comment]
Added: https://github.com/indivisable/EVContactsPicker/pull/1
