### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by raymond-auhwa** [edwardvalentini/EVContactsPicker#11]
There's a memory due to un-weak delegate.
In EVContactsPickerViewController at line 43: public var delegate : EVContactsPickerDelegate?
such deletgate need to be weak by letting EVContactsPickerDelegate extends class.

Leak can be verified in Profile.

Please fix.
Thanks

**Comment by edwardvalentini** [comment]
thanks for letting me know.. this has been fixed now.

**Comment by raymond-auhwa** [comment]
Good man.
Thanks a lot.

**Comment by edwardvalentini** [comment]
im going to close this issue
