### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by quiin** [edwardvalentini/EVContactsPicker#12]
Hi!, we've been using this Pod for a while now and we are now migrating our project to swift 4 and we are having issues migrating this particular Pod (Mainly because of the Nuke v4.1.2 dependency)

So we wanted to know if there's an upcomming migration to swift 4. I noted there's a commit regarding support for swift 3.2 & 4 but the readme still says swift 3 and I cannot build the project for swift 4.

Cheers!

**Comment by edwardvalentini** [comment]
The master branch is updated for swift 4 which takes care of the Nuke issue… There is still a UI issue that I need to fix… before its ready for a release.   If you have some time, definitely would appreciate a PR.
