### ISSUE TITLE
Example using Custom Data Source?

### ISSUE THREAD

**Issue by indivisable** [edwardvalentini/EVContactsPicker#8]
Is there any examples showcasing the use of custom data source?

**Comment by edwardvalentini** [comment]
no example yet.. if you want to submit a PR that would be great.

**Comment by indivisable** [comment]
Thanks @edwardvalentini, could you point me in right direction and I'll write an example, is there any specific functions for this?

Update:

Putting this here for docs:

```
  public init(externalDataSource: [EVContactProtocol]!) {
        self.init()
        self.useExternal = true
        self.externalDataSource = externalDataSource
        self.setup()
    }
```

**Comment by indivisable** [comment]
Here is a good example of how to use a custom data source:

https://github.com/dylan5394/FriendsLink/blob/209193dd31e206faeed7a54df69e84c733f5ed87/FriendsLink/FriendsTableViewController.swift
