### ISSUE TITLE
Passing prior selected contacts

### ISSUE THREAD

**Issue by indivisable** [edwardvalentini/EVContactsPicker#9]
Is it possible to pass in a object with the previous selected contacts? This way you can keep the state to allow user to edit and not start over again. If not this would be great feature.

Thanks for the awesome framework, hope I can contribute some more after holidays.

**Comment by edwardvalentini** [comment]
yes you can.

as long as your object conforms to EVContactProtocol you can pass in an array of contacts

**Comment by indivisable** [comment]
How would one go about doing this? 

I see selectedContacts

Would I do:

```
let contactPicker = EVContactsPickerViewController()
contactPicker.delegate = self
contactPicker.selectedContacts = existingSelectedContacts
...
```

**Comment by indivisable** [comment]
@edwardvalentini any tips here? I tried the above but does not seem to work. 

Trying to figure out what best way to pass the selected contacts back in after removing the view etc.

Thanks again

**Comment by indivisable** [comment]
Update: 

I found out how to use the external datasource and keep the state (however it does not select but that is fine) is there a way to SelectAllItems?

```
if (self.activeWho != nil) {
    contactPicker = EVContactsPickerViewController(externalDataSource: self.activeWho)
}else{
    contactPicker = EVContactsPickerViewController()
 }
...
```

Here is a good example of how to use a custom data source:

https://github.com/dylan5394/FriendsLink/blob/209193dd31e206faeed7a54df69e84c733f5ed87/FriendsLink/FriendsTableViewController.swift
